# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a3daa567b067b4d0e45c51eae5571a51c12407ef38f9198db572c46dde0756d272c963b769f41d29d8bc9b99c5271c34d2d219f0c4055e7d538ee6599c0fab9

test:
  secret_key_base: 0625e94d6d4e8487577c44375172e71da9b71c9cfe8512528424e42e47720e81856c662d987638cf5911d45564367e4b8167dbbce5b8c3aefb52e5b664e30668

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
