Scale.create!([
  {scale_name: "Ionian", c: true, c_sharp: false, d: true, d_sharp: false, e: true, f: true, f_sharp: false, g: true, g_sharp: false, a: true, a_sharp: false, b: true, history: ""},
  {scale_name: "Dorian", c: true, c_sharp: true, d: false, d_sharp: true, e: false, f: true, f_sharp: false, g: true, g_sharp: false, a: true, a_sharp: true, b: false, history: ""},
  {scale_name: "Phrygian", c: true, c_sharp: true, d: false, d_sharp: true, e: false, f: true, f_sharp: false, g: true, g_sharp: true, a: false, a_sharp: true, b: false, history: ""},
  {scale_name: "Mixolydian", c: true, c_sharp: false, d: true, d_sharp: false, e: true, f: true, f_sharp: false, g: true, g_sharp: false, a: true, a_sharp: true, b: false, history: ""},
  {scale_name: "Aeolian", c: true, c_sharp: false, d: true, d_sharp: true, e: false, f: true, f_sharp: false, g: true, g_sharp: true, a: false, a_sharp: true, b: false, history: ""},
  {scale_name: "Locrian (Minor Diminished)", c: true, c_sharp: true, d: false, d_sharp: true, e: false, f: true, f_sharp: true, g: false, g_sharp: true, a: false, a_sharp: true, b: false, history: ""},
  {scale_name: "Harmonic Minor", c: true, c_sharp: false, d: true, d_sharp: true, e: false, f: true, f_sharp: false, g: true, g_sharp: true, a: false, a_sharp: false, b: true, history: ""},
  {scale_name: "Diminished", c: true, c_sharp: false, d: true, d_sharp: true, e: false, f: true, f_sharp: true, g: false, g_sharp: true, a: true, a_sharp: false, b: true, history: ""},
  {scale_name: "Whole Tone", c: true, c_sharp: false, d: true, d_sharp: false, e: true, f: false, f_sharp: true, g: false, g_sharp: true, a: false, a_sharp: true, b: false, history: ""},
  {scale_name: "Blues Major", c: true, c_sharp: false, d: true, d_sharp: true, e: true, f: false, f_sharp: false, g: true, g_sharp: false, a: true, a_sharp: false, b: false, history: ""},
  {scale_name: "Blues Minor", c: true, c_sharp: false, d: false, d_sharp: true, e: false, f: true, f_sharp: true, g: true, g_sharp: false, a: false, a_sharp: true, b: false, history: ""},
  {scale_name: "Mixo-Blues", c: true, c_sharp: false, d: false, d_sharp: true, e: true, f: true, f_sharp: true, g: true, g_sharp: false, a: false, a_sharp: true, b: false, history: ""},
  {scale_name: "Enigmatic", c: true, c_sharp: true, d: false, d_sharp: false, e: true, f: false, f_sharp: true, g: false, g_sharp: true, a: false, a_sharp: true, b: true, history: ""},
  {scale_name: "6-Tone Symmetrical", c: true, c_sharp: true, d: false, d_sharp: false, e: true, f: true, f_sharp: false, g: false, g_sharp: true, a: true, a_sharp: false, b: false, history: ""},
  {scale_name: "Balinese", c: true, c_sharp: true, d: false, d_sharp: true, e: false, f: false, f_sharp: false, g: true, g_sharp: true, a: false, a_sharp: false, b: false, history: ""},
  {scale_name: "Javanese", c: true, c_sharp: true, d: false, d_sharp: true, e: false, f: true, f_sharp: false, g: true, g_sharp: false, a: true, a_sharp: true, b: false, history: ""},
  {scale_name: "Asian", c: true, c_sharp: false, d: false, d_sharp: true, e: false, f: false, f_sharp: false, g: true, g_sharp: false, a: true, a_sharp: true, b: false, history: ""},
  {scale_name: "Ancient Chinese", c: true, c_sharp: false, d: true, d_sharp: false, e: true, f: false, f_sharp: true, g: true, g_sharp: false, a: true, a_sharp: false, b: false, history: ""},
  {scale_name: "Chinese", c: true, c_sharp: false, d: false, d_sharp: false, e: true, f: false, f_sharp: true, g: true, g_sharp: false, a: false, a_sharp: false, b: true, history: ""},
  {scale_name: "Banshikicho", c: true, c_sharp: false, d: true, d_sharp: true, e: true, f: false, f_sharp: false, g: true, g_sharp: false, a: true, a_sharp: true, b: false, history: ""},
  {scale_name: "Oshikicho", c: true, c_sharp: false, d: true, d_sharp: true, e: false, f: true, f_sharp: false, g: true, g_sharp: false, a: true, a_sharp: true, b: false, history: ""},
  {scale_name: "In", c: true, c_sharp: true, d: true, d_sharp: false, e: false, f: true, f_sharp: false, g: true, g_sharp: true, a: true, a_sharp: false, b: false, history: ""},
  {scale_name: "Jaio", c: true, c_sharp: false, d: false, d_sharp: true, e: false, f: true, f_sharp: false, g: false, g_sharp: true, a: false, a_sharp: true, b: false, history: ""},
  {scale_name: "Hirajoshi", c: true, c_sharp: false, d: true, d_sharp: true, e: false, f: false, f_sharp: false, g: true, g_sharp: true, a: false, a_sharp: false, b: false, history: ""},
  {scale_name: "Kokinjoshi", c: true, c_sharp: true, d: false, d_sharp: false, e: false, f: true, f_sharp: false, g: true, g_sharp: false, a: false, a_sharp: true, b: false, history: ""},
  {scale_name: "Qing Yu", c: true, c_sharp: false, d: true, d_sharp: false, e: false, f: true, f_sharp: false, g: true, g_sharp: false, a: false, a_sharp: true, b: false, history: ""},
  {scale_name: "Ryosen", c: true, c_sharp: false, d: true, d_sharp: false, e: true, f: false, f_sharp: false, g: true, g_sharp: false, a: true, a_sharp: false, b: false, history: ""},
  {scale_name: "Ryukyu", c: true, c_sharp: false, d: false, d_sharp: false, e: true, f: true, f_sharp: false, g: true, g_sharp: false, a: false, a_sharp: false, b: true, history: ""},
  {scale_name: "Yo", c: true, c_sharp: false, d: true, d_sharp: false, e: false, f: true, f_sharp: false, g: true, g_sharp: false, a: true, a_sharp: false, b: false, history: ""},
  {scale_name: "Shakuhachi", c: true, c_sharp: false, d: false, d_sharp: true, e: false, f: true, f_sharp: false, g: true, g_sharp: false, a: false, a_sharp: true, b: false, history: ""},
  {scale_name: "Hindu", c: true, c_sharp: false, d: true, d_sharp: false, e: true, f: true, f_sharp: false, g: true, g_sharp: true, a: false, a_sharp: true, b: false, history: ""},
  {scale_name: "Bhairav Thaat", c: true, c_sharp: true, d: false, d_sharp: false, e: true, f: true, f_sharp: false, g: true, g_sharp: true, a: false, a_sharp: false, b: true, history: ""},
  {scale_name: "Eastern Minor", c: true, c_sharp: false, d: true, d_sharp: true, e: false, f: true, f_sharp: false, g: true, g_sharp: true, a: false, a_sharp: false, b: false, history: ""},
  {scale_name: "Middle Eastern", c: true, c_sharp: false, d: false, d_sharp: true, e: true, f: false, f_sharp: false, g: true, g_sharp: true, a: false, a_sharp: false, b: false, history: ""},
  {scale_name: "Mohammaden", c: true, c_sharp: false, d: true, d_sharp: true, e: false, f: true, f_sharp: false, g: true, g_sharp: true, a: false, a_sharp: false, b: true, history: ""},
  {scale_name: "Hungarian Major", c: true, c_sharp: false, d: false, d_sharp: true, e: true, f: false, f_sharp: true, g: true, g_sharp: false, a: true, a_sharp: true, b: false, history: ""},
  {scale_name: "Hungarian Minor", c: true, c_sharp: false, d: true, d_sharp: true, e: false, f: false, f_sharp: true, g: true, g_sharp: true, a: false, a_sharp: false, b: true, history: ""},
  {scale_name: "Persian", c: true, c_sharp: true, d: false, d_sharp: false, e: false, f: true, f_sharp: false, g: true, g_sharp: true, a: false, a_sharp: false, b: true, history: ""},
  {scale_name: "Romanian Minor", c: true, c_sharp: false, d: true, d_sharp: true, e: false, f: false, f_sharp: true, g: true, g_sharp: false, a: true, a_sharp: true, b: false, history: ""},
  {scale_name: "Spanish Gypsy", c: true, c_sharp: true, d: false, d_sharp: false, e: true, f: true, f_sharp: false, g: true, g_sharp: true, a: false, a_sharp: true, b: false, history: ""},
  {scale_name: "Adonai Malakh", c: true, c_sharp: true, d: true, d_sharp: true, e: false, f: true, f_sharp: false, g: true, g_sharp: false, a: true, a_sharp: true, b: false, history: ""},
  {scale_name: "Magen Abot", c: true, c_sharp: true, d: false, d_sharp: true, e: true, f: false, f_sharp: true, g: false, g_sharp: true, a: false, a_sharp: true, b: true, history: ""}
])
